### ISSUE TITLE
As a customer, I can delete a review I posted.

### ISSUE THREAD

**Issue by MinaSZ** [ahmedetefy/KodokyojinCoffeeFinder#56]

**Comment by MinaSZ** [comment]
@Ahmed-bastawisy please review the UMLs

**Comment by MinaSZ** [comment]
@alyakan please review the code

**Comment by MinaSZ** [comment]
@KareemTarek4 please review the documentation

**Comment by alyakan** [comment]
Code Reviewed @MinaSZ

**Comment by KareemTarek4** [comment]
Documentation reviewed , good job !
